let prod = [
    {
        name: "Phone",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/flat-set-1/64/flat_set_1-25-64.png",
        description: "Amazing",
        price: "34000",
        category: "Electronics",
    },
    {
        name: "TV",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/solid-amenities-icon-set/64/Cable_TV_2-64.png",
        description: "Amazing",
        price: "34000",
        category: "Electronics",
        seller: "Sansui",
    },
    {
        name: "AC",
        imageUrl: "https://cdn4.iconfinder.com/data/icons/real-estate-349/24/air_conditioner_ac_con_cooler_temperature_household-64.png",
        description: "Amazing",
        price: "25000",
        category: "Electronics",
        seller: "Tata",
    },
    {
        name: "Frideg",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/solid-amenities-icon-set/64/Refrigerator_2-64.png",
        description: "Cool",
        price: "30000",
        category: "Electronics",
        seller: "Dell",
    },
    {
        name: "Bat",
        imageUrl: "https://cdn1.iconfinder.com/data/icons/sports-199/48/18-256.png",
        description: "Easy",
        price: 2000,
        category: "sports",
        seller: "Mamba",
    },
    {
        name: "Boll",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/sports-85/512/bowling_pin_bol_game_sport-64.png",
        description: "Easy",
        price: 500,
        category: "sports",
        seller: "Mamba",
    },
    {
        name: "Helmet",
        imageUrl: "https://cdn2.iconfinder.com/data/icons/thesquid-ink-40-free-flat-icon-pack/64/football-helmet-64.png",
        description: "Easy",
        price: 5000,
        category: "sports",
        seller: "Mamba",
    },
    {
        name: "Pads",
        imageUrl: "https://cdn1.iconfinder.com/data/icons/cricket-15/73/2-64.png",
        description: "Easy to wear",
        price: 2500,
        category: "sports",
        seller: "Mamba",
    },
    {
        name: "Shirt",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/fashion-beauty-vol-1/512/shirt_long_sleeve_clothes-64.png",
        description: "Easy to wear",
        price: 650,
        category: "Fashion",
        seller: "H&M",
    },
    {
        name: "Pant",
        imageUrl: "https://cdn1.iconfinder.com/data/icons/clothes-and-outfit-vol-1-1/128/jeans_pants_fashion_outfit_clothes_shopping-64.png",
        description: "Easy to wear",
        price: 700,
        category: "Fashion",
        seller: "H&M",
    },
    {
        name: "T-shirt",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/sketchy-basic-icons/94/t-shirt-64.png",
        description: "Easy to wear",
        price: 500,
        category: "Fashion",
        seller: "H&M",
    },
    {
        name: "Kurta",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/indian-5/491/indian-man-kurta-tradition-costume-256.png",
        description: "Easy to wear",
        price: 1500,
        category: "Fashion",
        seller: "H&M",
    },
    {
        name: "Wheat",
        imageUrl: "https://cdn2.iconfinder.com/data/icons/miscellaneous-290-line/128/flour_meal_farina_wheat_grain_bread_cereal_bag_nutrition-64.png",
        description: "Easy to Eat",
        price: 1500,
        category: "Food",
        seller: "Rajdhani",
    },

    {
        name: "Oil",
        imageUrl: "https://cdn4.iconfinder.com/data/icons/epic-outlines/30/oil_can-64.png",
        description: "Easy to wear",
        price: 500,
        category: "Food",
        seller: "Rajdhani",
    },
    {
        name: "Rice",
        imageUrl: "https://cdn3.iconfinder.com/data/icons/food-set-2-1/91/Food_C167-64.png",
        description: "Easy to wear",
        price: 2100,
        category: "Food",
        seller: "Rajdhani",
    }
    ,
    {
        name: "Milk",
        imageUrl: "https://cdn2.iconfinder.com/data/icons/bakery-kitchen-3/512/milk-drink-bottle-64.png",
        description: "Easy to eat",
        price: 25,
        category: "Food",
        seller: "Cow Milk",
    }
]
let data = JSON.stringify(prod)
console.log(data);